<?php
/**
* @file
* A description of what your module does.
*/

use Drupal\node\NodeInterface;
use Drupal\Core\Link;
use Symfony\Component\HttpFoundation\RedirectResponse;

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function jir_interface_node_insert(NodeInterface $node) {

  if ($node->bundle() == 'employer') {
    $actualLink = Link::createFromRoute(t('Post Job'), 'node.add', ['node_type' => 'job']);
    $node->set("field_employer_post_job_link", $actualLink->getUrl()->toUriString() . "?edit[field_job_company_name]=" . $node->id());
    $node->setNewRevision(FALSE);
    $node->save();
    return new RedirectResponse("/node/add/job?edit[field_job_company_name]=" . $node->id()); //Not working
  }
}

/**
 * Implements hook_entity_insert().
 */
function jir_interface_entity_insert(EntityInterface $entity) {
  if ($entity->bundle() == 'job'){
    Drupal::cache('render')->deleteAll();
  }
}

/**
 * Implements hook_entity_update().
 */
function jir_interface_entity_update(EntityInterface $entity) {
  if ($entity->bundle() == 'job'){
    Drupal::cache('render')->deleteAll();
  }
}